INSERT INTO ACTOR(ACTOR_NAME) VALUES ('TESTE_ATOR1');
INSERT INTO ACTOR(ACTOR_NAME) VALUES ('TESTE_ATOR2');

INSERT INTO director(DIRECTOR_NAME) VALUES ('TESTE_DIRETOR1');
INSERT INTO director(DIRECTOR_NAME) VALUES ('TESTE_DIRETOR2');

INSERT INTO type(CLASS_VALUE, TYPE_NAME, RETURN_DATE) VALUES (1, 'TESTE_CLASSE1', 10);
INSERT INTO type(CLASS_VALUE, TYPE_NAME, RETURN_DATE) VALUES (2, 'TESTE_CLASSE2', 5);
INSERT INTO TITLE(TITLE_NAME, SYNOPSIS, CATEGORY) VALUES ('FILME_1', 'SINOPSE DE FILME', 'CATEGORIA');
INSERT INTO TITLE(TITLE_NAME, SYNOPSIS, CATEGORY) VALUES ('THE GODFATHER', '123', 'CRIME');
INSERT INTO ITEM(SERIAL_NUMBER, ITEM_TYPE) VALUES (1234, 'TESTE_CATEGORIA');